site_name: stlog
repo_url: https://github.com/fabien-marty/stlog

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 2

plugins:
  - search
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - macros

nav:
  - index.md
  - quickstart.md
  - usage.md
  - tuning.md
  - extend.md
  - faq.md
  - dev.md

extra:
  twelvefactorapp: "[Twelve-Factor App](https://12factor.net/)"
  pythonlogging: "[standard python logging](https://docs.python.org/3/library/logging.html)"
  contextvars: "[contextvars](https://docs.python.org/3/library/contextvars.html)"
  rich: "[the rich library](https://github.com/Textualize/rich)"
  pathprefix: ""
  _apilink: "https://fabien-marty.github.io/stlog/stlog/"
  coverage: "https://fabien-marty.github.io/stlog/coverage"
  logfmt: "[logfmt format](https://brandur.org/logfmt)"
